version: '2'
services:
  redis:
    image: "redis:alpine"
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASS}
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    env_file:
      - .env
    restart: always
  go-searchme:
    build: .
    image: jhawk7/go-searchme
    env_file:
      - .env
    ports:
      - "8888:8888"
    restart: always
    depends_on: [redis]
